	#define TOKEN_INICIO 1
	#define TOKEN_FIN 2
	#define TOKEN_VECTOR 3
	#define TOKEN_ENTERO 4
	#define TOKEN_LOGICO 5
	#define TOKEN_MARIO 6
	#define TOKEN_RODRIGO 7
	#define TOKEN_MARTINEZ 8
	#define TOKEN_ANGELES 9